sudo: required
services:
  - docker


before_install:
  - docker build -t ksondz/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true ksondz/react-test npm run test

after_success:
  - docker build -t ksondz/multi-client ./client
  - docker build -t ksondz/multi-nginx ./nginx
  - docker build -t ksondz/multi-server ./server
  - docker build -t ksondz/multi-worker ./worker

  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin

  - docker push ksondz/multi-client
  - docker push ksondz/multi-nginx
  - docker push ksondz/multi-server
  - docker push ksondz/multi-worker
